# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBwp_gN30rGDZFPdxGQH524cLkqq57hS
"""

students = {}

def add_student():
    name = input("Enter student name: ").strip()
    score = int(input("Enter student score: "))
    students[name] = score
    print("Student added successfully.")

def view_all():
    print("\n---- All Students ----")
    if not students:
        print("No students found.")
    else:
        for name, score in students.items():
            print(f"{name}: {score}")

def search_student():
    name = input("\nEnter student name to search: ").strip()
    if name in students:
        print(f"{name}'s score is {students[name]}")
    else:
        print("Student not found.")

def remove_student():
    name = input("\nEnter student name to remove: ").strip()
    if name in students:
        del students[name]
        print("Student removed successfully.")
    else:
        print("Student not found.")

def main():
    while True:
        print("\n---- Student Score Tracker ----")
        print("1. Add Student")
        print("2. View All Students")
        print("3. Search Student")
        print("4. Remove Student")
        print("5. Exit")
        choice = input("Enter your choice: ").strip()

        if choice == '1':
            add_student()
        elif choice == '2':
            view_all()
        elif choice == '3':
            search_student()
        elif choice == '4':
            remove_student()
        elif choice == '5':
            print("Exiting the application. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 5.")

if __name__ == "__main__":
    main()